### ISSUE TITLE
Crash on Restore Database

### ISSUE THREAD

**Issue by shuvashish76** [you-apps/VibeYou#59]
### Steps to reproduce

1. Install MellowMusic
2. Add some music to favourites on MellowMusic
3. Backup Databse
4. Uninstall MellowMusic
5. Install Vive You
6. Restore existing database
See error.

### Expected behavior

Existing MellowMusic users should able to restore their existing Databse to switch over to new app.

### Actual behavior

App crashed.

### Vibe You version

1.0

### Android version

Android 12

### Other details

Logs:
```
FATAL EXCEPTION: main
Process: app.suhasdissa.vibeyou, PID: 30661
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: ada7c6c2bcd1884e04cc9a6260733689, found: 6cad20a0151a96584ece67074c8071a8
	at q5.z.e(Unknown Source:96)
	at v5.f.onOpen(Unknown Source:15)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at v5.f.g(Unknown Source:4)
	at v5.f.m(Unknown Source:63)
	at v5.f.a(Unknown Source:21)
	at v5.g.getWritableDatabase(Unknown Source:9)
	at q5.y.b(Unknown Source:4)
	at q5.y.j(Unknown Source:8)
	at s8.w.r1(Unknown Source:11)
	at e6.f.a(Unknown Source:32)
	at e6.f.call(Unknown Source:6)
	at q5.c.p(Unknown Source:83)
	at c8.a.j(Unknown Source:8)
	at s8.c0.run(Unknown Source:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: x8.f: [o1{Cancelling}@17ea8c9, Dispatchers.Main.immediate]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Vibe You and MellowMusic are not compatible with each other, users are required to use a database export from VibeYou in order to import it in Vibe You.
